import { projectImage, projectLogo } from "@/constant/imagePath";
import { BiArea, BiBath, BiBed, BiCar } from "react-icons/bi";

export const projectsDataBox = Array.from({ length: 6 }).map(() => {
  return {
    name: "Project Name Here",
    location: "Serves Eldorado, OH",
    logo: projectLogo,
    image: projectImage,
  };
});
export const projectsDataTable = Array.from({ length: 10 }).map((_, index) => {
  return {
    id: index + 1,
    logo: projectLogo,
    name: "Project Name",
    location: "New York, USA",
    projectContact: 12345678901,
    subscriptionPlan: "Lite",
  };
});

export const projectDetailData = [
  {
    id: "STK001",
    name: "Product A",
    type: "Type A",
    width: "10cm",
    depth: "15cm",
    size: "Medium",
    contact: "John Doe",
    status: "reserved",
  },
  {
    id: "STK002",
    name: "Product B",
    type: "Type B",
    width: "20cm",
    depth: "25cm",
    size: "Large",
    contact: "Jane Smith",
    status: "available",
  },
  {
    id: "STK003",
    name: "Product C",
    type: "Type C",
    width: "15cm",
    depth: "20cm",
    size: "Small",
    contact: "Alice Johnson",
    status: "sold",
  },
  {
    id: "STK004",
    name: "Product D",
    type: "Type D",
    width: "12cm",
    depth: "18cm",
    size: "Medium",
    contact: "Bob Brown",
    status: "available",
  },
  {
    id: "STK005",
    name: "Product E",
    type: "Type E",
    width: "25cm",
    depth: "30cm",
    size: "Large",
    contact: "Eva White",
    status: "reserved",
  },
  {
    id: "STK006",
    name: "Product F",
    type: "Type F",
    width: "18cm",
    depth: "22cm",
    size: "Small",
    contact: "Michael Johnson",
    status: "sold",
  },
  {
    id: "STK007",
    name: "Product G",
    type: "Type G",
    width: "8cm",
    depth: "10cm",
    size: "Medium",
    contact: "Sarah Davis",
    status: "available",
  },
  {
    id: "STK008",
    name: "Product H",
    type: "Type H",
    width: "22cm",
    depth: "28cm",
    size: "Large",
    contact: "David Wilson",
    status: "reserved",
  },
  {
    id: "STK009",
    name: "Product I",
    type: "Type I",
    width: "16cm",
    depth: "21cm",
    size: "Small",
    contact: "Emily Taylor",
    status: "sold",
  },
  {
    id: "STK010",
    name: "Product J",
    type: "Type J",
    width: "30cm",
    depth: "35cm",
    size: "Large",
    contact: "William Martinez",
    status: "available",
  },
];

export const newProjectDetailArr = [
  {
    id: 101,
    icon: "shop",
    status: "available",
    name: "Apartment 101",
    image: "/images/project-logo.png",
    type: "Industrial",
    description: "Description for Apartment 101, a industrial property.",
    level: 8,
    aspect: "East",
    beds: 1,
    baths: 1,
    living: 1,
    cars: 1,
    price: 155523,
    frontage: 36,
    depth: 101,
    size: 3636,
    internal: 2727,
    external: 909,
    total: 3636,
    downloadLink: "https://example.com/industrial0.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 102,
    icon: "school",
    status: "reserved",
    name: "Lot 102",
    image: "/images/project-logo.png",
    type: "Commercial",
    description: "Description for Lot 102, a commercial property.",
    level: 5,
    aspect: "West",
    beds: 3,
    baths: 0,
    living: 1,
    cars: 0,
    price: 352702,
    frontage: 78,
    depth: 23,
    size: 1794,
    internal: 1345.5,
    external: 448.5,
    total: 1794,
    downloadLink: "https://example.com/commercial1.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 103,
    icon: "book",
    status: "sold",
    name: "Title 103",
    image: "/images/project-logo.png",
    type: "Recreational",
    description: "Description for Title 103, a recreational property.",
    level: 4,
    aspect: "West",
    beds: 0,
    baths: 1,
    living: 1,
    cars: 3,
    price: 289625,
    frontage: 96,
    depth: 51,
    size: 4896,
    internal: 3672,
    external: 1224,
    total: 4896,
    downloadLink: "https://example.com/recreational2.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 104,
    icon: "playground",
    status: "available",
    name: "Hanger 104",
    image: "/images/project-logo.png",
    type: "Commercial",
    description: "Description for Hanger 104, a commercial property.",
    level: 1,
    aspect: "South",
    beds: 1,
    baths: 0,
    living: 1,
    cars: 3,
    price: 267685,
    frontage: 20,
    depth: 62,
    size: 1240,
    internal: 930,
    external: 310,
    total: 1240,
    downloadLink: "https://example.com/commercial3.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 105,
    icon: "bus",
    status: "reserved",
    name: "Mooring 105",
    image: "/images/project-logo.png",
    type: "Residential",
    description: "Description for Mooring 105, a residential property.",
    level: 6,
    aspect: "West",
    beds: 2,
    baths: 2,
    living: 0,
    cars: 2,
    price: 228771,
    frontage: 103,
    depth: 49,
    size: 5047,
    internal: 3785.25,
    external: 1261.75,
    total: 5047,
    downloadLink: "https://example.com/residential4.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 106,
    icon: "pin",
    status: "sold",
    name: "Title 106",
    image: "/images/project-logo.png",
    type: "Commercial",
    description: "Description for Title 106, a commercial property.",
    level: 0,
    aspect: "West",
    beds: 4,
    baths: 2,
    living: 0,
    cars: 3,
    price: 185683,
    frontage: 55,
    depth: 18,
    size: 990,
    internal: 742.5,
    external: 247.5,
    total: 990,
    downloadLink: "https://example.com/commercial5.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 107,
    icon: "train",
    status: "reserved",
    name: "Pontoon 107",
    image: "/images/project-logo.png",
    type: "Industrial",
    description: "Description for Pontoon 107, a industrial property.",
    level: 1,
    aspect: "East",
    beds: 3,
    baths: 0,
    living: 0,
    cars: 2,
    price: 262019,
    frontage: 22,
    depth: 66,
    size: 1452,
    internal: 1089,
    external: 363,
    total: 1452,
    downloadLink: "https://example.com/industrial6.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 108,
    icon: "shopping cart",
    status: "available",
    name: "Mooring 108",
    image: "/images/project-logo.png",
    type: "Industrial",
    description: "Description for Mooring 108, a industrial property.",
    level: 4,
    aspect: "West",
    beds: 3,
    baths: 2,
    living: 0,
    cars: 0,
    price: 203324,
    frontage: 10,
    depth: 42,
    size: 420,
    internal: 315,
    external: 105,
    total: 420,
    downloadLink: "https://example.com/industrial7.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 109,
    icon: "hospital",
    status: "sold",
    name: "Townhouse 109",
    image: "/images/project-logo.png",
    type: "Recreational",
    description: "Description for Townhouse 109, a recreational property.",
    level: 2,
    aspect: "South",
    beds: 1,
    baths: 2,
    living: 0,
    cars: 1,
    price: 350973,
    frontage: 96,
    depth: 92,
    size: 8832,
    internal: 6624,
    external: 2208,
    total: 8832,
    downloadLink: "https://example.com/recreational8.pdf",
    enquiryLink: "Enquire Now",
  },
  {
    id: 110,
    icon: "playground",
    status: "reserved",
    name: "Pontoon 110",
    image: "/images/project-logo.png",
    type: "Residential",
    description: "Description for Pontoon 110, a residential property.",
    level: 7,
    aspect: "West",
    beds: 2,
    baths: 2,
    living: 0,
    cars: 0,
    price: 485579,
    frontage: 39,
    depth: 29,
    size: 1131,
    internal: 848.25,
    external: 282.75,
    total: 1131,
    downloadLink: "https://example.com/residential9.pdf",
    enquiryLink: "Enquire Now",
  },
];

export const subscriptionArr = [
  {
    _id: "1",
    type: "Basic",
    price: "Free Trial",
    period: "7 Days",
    description: "Included Features",
    features: ["Standard Plan", "100 mb S3 Storage"],
  },
  {
    _id: "2",
    type: "Lite",
    price: "$45",
    period: "Per Project/Per Month",
    description: "Included Features",
    features: [
      "Create Embeddable Project Link",
      "Basic Icons For Point",
      "Limited Data Entry Columns",
      "250 mb upload limit",
    ],
  },
  {
    _id: "3",
    type: "Standard",
    price: "$480",
    period: "Per Project/Per Month",
    description: "All Lite Features Plus",
    features: [
      "Create Embeddable Project Link",
      "Larger Icons For Point",
      "Extensive Data Entry Columns",
      "1 GB S3 Storage",
    ],
  },
];

export const billingData = [
  {
    invoiceNumber: "INV001",
    name: "Project X",
    billingDate: "2024-06-01",
    packageName: "Lite",
    price: "$50",
  },
  {
    invoiceNumber: "INV002",
    name: "Project Y",
    billingDate: "2024-06-05",
    packageName: "Basic",
    price: "$100",
  },
  {
    invoiceNumber: "INV003",
    name: "Project Z",
    billingDate: "2024-06-10",
    packageName: "Standard",
    price: "$150",
  },
  {
    invoiceNumber: "INV004",
    name: "Project W",
    billingDate: "2024-06-15",
    packageName: "Lite",
    price: "$50",
  },
  {
    invoiceNumber: "INV005",
    name: "Project V",
    billingDate: "2024-06-20",
    packageName: "Basic",
    price: "$100",
  },
  {
    invoiceNumber: "INV006",
    name: "Project U",
    billingDate: "2024-06-25",
    packageName: "Standard",
    price: "$150",
  },
  {
    invoiceNumber: "INV007",
    name: "Project T",
    billingDate: "2024-06-30",
    packageName: "Lite",
    price: "$50",
  },
  {
    invoiceNumber: "INV008",
    name: "Project S",
    billingDate: "2024-07-05",
    packageName: "Basic",
    price: "$100",
  },
  {
    invoiceNumber: "INV009",
    name: "Project R",
    billingDate: "2024-07-10",
    packageName: "Standard",
    price: "$150",
  },
  {
    invoiceNumber: "INV010",
    name: "Project Q",
    billingDate: "2024-07-15",
    packageName: "Lite",
    price: "$50",
  },
];

export const projectObj = {
  backgroundImg: "/images/dummy_canvas_image.jpg",
  splashScreenLogo: "/images/project-logo.png",
  name: "Project Name",
  points: [
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 71.8432919954904,
      y: 45.5467869222097,
    },
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 87.69729425028183,
      y: 38.55693348365276,
    },
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 57.16600901916573,
      y: 37.0913190529876,
    },
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 75.26775648252536,
      y: 51.40924464487034,
    },
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 68.03833145434047,
      y: 36.3021420518602,
    },
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 77.55073280721531,
      y: 44.7576099210823,
    },
    {
      status: "available",
      title: "Point Title",
      type: "house",
      level: "1",
      aspect: "10",
      address: "Shadow Creek West  |  Plat 1  |  Lot# 32",
      addressTwo: "18137 Hidden Knoll Clive, IA",
      sqft: "0.48 Acres",
      image: "/images/projectImage.png",
      x: 57.82835400225479,
      y: 54.56595264937994,
    },
  ],
};

export const pointData = {
  title: "Lot 501",
  status: "available",
  image: "/images/projectImage.png",
  price: "$500,00",
  frontage: "18m",
  depth: "34m",
  area: "623m",
  amenities: [
    { icon: <BiBed />, value: "3 Bed" },
    { icon: <BiBath />, value: "2 Bath" },
    { icon: <BiArea />, value: "623 Sq Ft" },
    { icon: <BiCar />, value: "1 Car" },
  ],
};
